import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Typography } from '@mui/material';
import { getUserState, setName, setEmail } from '../store/slices/userSlice';
import Card from '../ui/components/Card';
import { useDispatch, useSelector } from '../store/store';
import styles from '../styles/Home.module.css';

/**
 * A simple home page that pulls user info from redux-toolkit and displays.
 * Additionally it displays some cards for no reason.
 *
 * @constructor
 */
const Home: NextPage = () => {
  const dispatch = useDispatch();
  const { name, email } = useSelector(getUserState);

  React.useEffect(() => {
    setTimeout(() => {
      dispatch(setName('Öney'));
      dispatch(setEmail('sulhadin@hotmail.com'));
    }, 2000);
  });

  console.log('user info', name, email);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="h1" component="h2" className={styles.title}>
          Hi <>{name}</>
        </Typography>

        <p className={styles.description}>
          <code className={styles.code}>Something is wrong I can feel it!</code>
        </p>

        <div className={styles.grid}>
          <Card
            title={'Box 1'}
            text={'Find in-depth information about Next.js features and API.'}
          />
          <Card
            title={'Box 2'}
            text={'Find in-depth information about Next.js features and API.'}
          />
          <Card
            title={'Box 3'}
            text={'Find in-depth information about Next.js features and API.'}
          />
          <Card
            title={'Box 4'}
            text={'Find in-depth information about Next.js features and API.'}
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
